### ISSUE TITLE
Enrichment : error with format

### ISSUE THREAD

**Issue by alvsan1** [SmartDataAnalytics/DL-Learner#80]
Hi ,
I'm run in Ubuntu
DL-Learner/dllearner-ext-1.4.0/bin/enrichment -e http://... -o results.ttl -f turtle -r http://example.com/father#female

After the whole process the error is:

Exception in thread "main" java.lang.NullPointerException
	at org.dllearner.cli.Enrichment.toRDF(Enrichment.java:662)
	at org.dllearner.cli.Enrichment.toRDF(Enrichment.java:613)
	at org.dllearner.cli.Enrichment.main(Enrichment.java:1140)

Without formatting runs without has errors.

Thanks for any help !!!

**Comment by SimonBin** [comment]
hi, thanks for the report. I don't have the error :-( what java version is installed on your system?

**Comment by alvsan1** [comment]
Hi, 
I'm use openjdk version "1.8.0_265" .

thanks!!!-
